/* Learning records, sync-code transfer, and unseen-first rotation. */
(()=>{
const KEY='sw_stats',SEEN='sw_seen_v1';
const empty=()=>({attempts:[],questions:{}});
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||empty()}catch{return empty()}};
const seenGet=()=>{try{return JSON.parse(localStorage.getItem(SEEN)||'{}')||{}}catch{return {}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function panel(){let p=document.getElementById('localProgressPanel');if(p)return p;p=document.createElement('section');p.id='localProgressPanel';p.className='card hidden';p.innerHTML='<h2>📚 我的學習紀錄</h2><p class="muted">紀錄保存在本機。跨裝置請在舊裝置匯出同步碼，再到新裝置匯入。</p><div id="localSummary"></div><div class="actions"><button onclick="localExport()">📤 匯出同步碼</button><button class="secondary" onclick="localImportPrompt()">📥 匯入同步碼</button><button class="secondary" onclick="localExportFile()">下載備份檔</button><button class="secondary" onclick="localShowHistory()">歷次模擬考</button><button class="secondary" onclick="goHome()">回首頁</button></div><div id="localHistory"></div>';document.querySelector('.wrap').appendChild(p);return p}
function render(){let s=get(),a=s.attempts||[],qs=Object.values(s.questions||{}),t=qs.reduce((n,q)=>n+(q.total||0),0),r=qs.reduce((n,q)=>n+(q.right||0),0);panel().querySelector('#localSummary').innerHTML='<div class="statgrid"><div class="stat"><small>模擬考次數</small><b>'+a.length+'</b></div><div class="stat"><small>累積作答</small><b>'+t+'</b></div><div class="stat"><small>累積正確率</small><b>'+(t?Math.round(r/t*100):0)+'%</b></div></div>'}
window.showStats=()=>{['home','quiz','result','review'].forEach(id=>document.getElementById(id)?.classList.add('hidden'));render();panel().classList.remove('hidden');localShowHistory()};
window.localShowHistory=()=>{let a=get().attempts||[],e=panel().querySelector('#localHistory');e.innerHTML='<h3>歷次模擬考</h3>'+(a.length?a.slice(0,50).map((x,i)=>'<div class="wrong"><b>第 '+(a.length-i)+' 次</b><p>'+esc(new Date(x.at).toLocaleString('zh-TW'))+'｜'+x.score+' 分｜'+x.correct+'/'+x.total+'</p></div>').join(''):'<p class="muted">尚無紀錄。</p>')};
function pack(){return {format:'socialwork-sync',version:1,stats:get(),seen:seenGet()}}
function encode(o){let b=new TextEncoder().encode(JSON.stringify(o)),s='';b.forEach(x=>s+=String.fromCharCode(x));return 'SW1'+btoa(s).split('+').join('-').split('/').join('_').replace(/=+$/,'')}
function decode(s){s=String(s).trim().replace(/^SW1/,'').split('-').join('+').split('_').join('/');s+='='.repeat((4-s.length%4)%4);let b=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(b))}
window.localExport=()=>{let code=encode(pack()),w=window.open('','_blank');if(w){w.document.write('<meta charset="utf-8"><textarea style="width:98%;height:80vh"></textarea>');let t=w.document.querySelector('textarea');t.value=code;t.select()}else prompt('請複製同步碼：',code)};
window.localImportPrompt=()=>{let s=prompt('貼上舊裝置同步碼（SW1 開頭）：');if(!s)return;try{let d=decode(s);if(d.format!=='socialwork-sync'||d.version!==1||!d.stats)throw Error();if(!confirm('合併同步碼與本機紀錄？'))return;let old=get(),m=new Map();[...(old.attempts||[]),...(d.stats.attempts||[])].forEach(a=>m.set([a.at,a.score,a.total,a.correct].join('|'),a));let qs={...old.questions};Object.entries(d.stats.questions||{}).forEach(([id,q])=>{let a=qs[id]||{};qs[id]={...a,...q};['wrong','right','total','uncertain'].forEach(k=>qs[id][k]=Math.max(+a[k]||0,+q[k]||0))});localStorage.setItem(KEY,JSON.stringify({attempts:[...m.values()].sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,100),questions:qs}));let seen=seenGet();Object.entries(d.seen||{}).forEach(([k,v])=>seen[k]=[...new Set([...(seen[k]||[]),...(Array.isArray(v)?v:[])])]);localStorage.setItem(SEEN,JSON.stringify(seen));render();localShowHistory();alert('匯入完成，紀錄已合併。')}catch{alert('同步碼無效，請重新複製。')}};
window.localExportFile=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(pack(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='socialwork-backup.json';a.click();URL.revokeObjectURL(u)};
const originalStart=window.startQuiz;window.startQuiz=function(){let pool=filter(),count=document.getElementById('count').value,n=Math.min(count==='full'?pool.length:Number(count),pool.length);if(!pool.length)return alert('沒有符合條件的題目');let k=document.getElementById('year').value+'|'+document.getElementById('subject').value,s=seenGet(),done=new Set((s[k]||[]).map(String)),fresh=shuffle(pool.filter(q=>!done.has(String(q.id)))),chosen=fresh.slice(0,n);if(chosen.length<n){let ids=new Set(chosen.map(q=>String(q.id)));chosen.push(...shuffle(pool.filter(q=>!ids.has(String(q.id)))).slice(0,n-chosen.length))}quiz=chosen;chosen.forEach(q=>done.add(String(q.id)));s[k]=[...done];localStorage.setItem(SEEN,JSON.stringify(s));cur=0;ans={};uncertain={};lastWrong=[];lastUncertain=[];startedAt=Date.now();clearInterval(timerId);timerId=setInterval(updateTimer,1000);['home','result','review'].forEach(id=>document.getElementById(id).classList.add('hidden'));document.getElementById('quiz').classList.remove('hidden');panel().classList.add('hidden');render();updateTimer()};
})();