/* Local learning records, sync-code transfer, and unseen-first question rotation. */
(function(){
  const KEY='sw_stats', SEEN='sw_seen_v1';
  const empty=()=>({attempts:[],questions:{}});
  function get(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||empty()}catch(e){return empty()}}
  function put(v){localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new Event('sw-local-changed'))}
  function getSeen(){try{return JSON.parse(localStorage.getItem(SEEN)||'{}')||{}}catch(e){return {}}}
  function setSeen(v){localStorage.setItem(SEEN,JSON.stringify(v))}
  function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function panel(){let p=document.getElementById('localProgressPanel');if(p)return p;p=document.createElement('section');p.id='localProgressPanel';p.className='card hidden';p.innerHTML='<h2>📚 我的學習紀錄</h2><p class="muted">紀錄保存在本機。跨裝置請使用同步碼：舊裝置匯出，新裝置匯入；不需註冊或雲端登入。</p><div id="localSummary"></div><div class="actions"><button onclick="localShowHistory()">📊 歷次模擬考</button><button onclick="localExport()">📤 匯出同步碼</button><button class="secondary" onclick="localImportPrompt()">📥 匯入同步碼</button><button class="secondary" onclick="localExportFile()">下載備份檔</button><button class="danger" onclick="localClear()">清除本機紀錄</button><button class="secondary" onclick="goHome()">回首頁</button></div><div id="localHistory"></div>';document.querySelector('.wrap').appendChild(p);return p}
  function render(){const p=panel(),s=get(),a=s.attempts||[],qs=s.questions||{},vals=Object.values(qs),total=vals.reduce((n,q)=>n+(q.total||0),0),wrong=vals.reduce((n,q)=>n+(q.wrong||0),0),right=vals.reduce((n,q)=>n+(q.right||0),0);p.querySelector('#localSummary').innerHTML='<div class="statgrid"><div class="stat"><small>模擬考次數</small><b>'+a.length+'</b></div><div class="stat"><small>累積作答</small><b>'+total+'</b></div><div class="stat"><small>累積正確率</small><b>'+(total?Math.round(right/total*100):0)+'%</b></div><div class="stat"><small>錯題次數</small><b>'+wrong+'</b></div></div>'}
  window.showStats=function(){['home','quiz','result','review'].forEach(id=>{const e=document.getElementById(id);if(e)e.classList.add('hidden')});render();panel().classList.remove('hidden');localShowHistory()};
  window.localShowHistory=function(){const a=get().attempts||[],e=document.getElementById('localHistory');e.innerHTML='<h3>歷次模擬考</h3>'+(a.length?a.slice(0,50).map((x,i)=>'<div class="wrong"><b>第 '+(a.length-i)+' 次</b><p>'+esc(new Date(x.at).toLocaleString('zh-TW'))+'｜'+x.score+' 分｜'+x.correct+'/'+x.total+'｜不確定 '+(x.uncertain||0)+'</p></div>').join(''):'<p class="muted">尚無紀錄。</p>')};
  function packageData(){return {format:'socialwork-sync',version:1,exportedAt:new Date().toISOString(),stats:get(),seen:getSeen()}}
  function encode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
  function decode(code){code=String(code).trim().replace(/^SW1\s*/,'').replace(/-/g,'+').replace(/_/g,'/');code+='='.repeat((4-code.length%4)%4);const bin=atob(code),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
  window.localExport=function(){const code='SW1'+encode(packageData());const w=window.open('','_blank');if(w){w.document.write('<meta charset="utf-8"><title>同步碼</title><textarea style="width:98%;height:80vh;font:14px monospace"></textarea>');w.document.querySelector('textarea').value=code;w.document.querySelector('textarea').select()}else prompt('請複製同步碼：',code)};
  window.localImportPrompt=function(){const code=prompt('貼上舊裝置的同步碼（SW1 開頭）：');if(code)importPackage(decode(code))};
  function merge(old,inc){const out={attempts:[],questions:{}};const map=new Map();[...(old.attempts||[]),...(inc.attempts||[])].forEach(a=>{const k=[a.at,a.score,a.total,a.correct].join('|');if(!map.has(k))map.set(k,a)});out.attempts=[...map.values()].sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,100);const ids=new Set([...Object.keys(old.questions||{}),...Object.keys(inc.questions||{})]);ids.forEach(id=>{const a=(old.questions||{})[id]||{},b=(inc.questions||{})[id]||{},q={...a,...b};['wrong','right','total','uncertain'].forEach(k=>q[k]=Math.max(Number(a[k]||0),Number(b[k]||0)));q.reasons={...(a.reasons||{}),...(b.reasons||{})};out.questions[id]=q});return out}
  function importPackage(d){if(!d||d.format!=='socialwork-sync'||d.version!==1||!d.stats||!Array.isArray(d.stats.attempts)||!d.stats.questions)throw Error('格式錯誤');if(!confirm('將合併同步碼與本機紀錄，不會直接覆蓋。繼續？'))return;put(merge(get(),d.stats));const seen=getSeen();Object.entries(d.seen||{}).forEach(([k,v])=>seen[k]=[...new Set([...(seen[k]||[]),...(v||[])])]);setSeen(seen);render();localShowHistory();alert('匯入完成，紀錄已合併。')}
  window.localExportFile=function(){const blob=new Blob([JSON.stringify(packageData(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='socialwork-sync-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(url)};
  window.localClear=function(){if(!confirm('確定清除本機所有學習紀錄與已刷題進度？'))return;localStorage.removeItem(KEY);localStorage.removeItem(SEEN);render();localShowHistory()};
  const oldStart=window.startQuiz;
  if(typeof oldStart==='function')window.startQuiz=function(){const p=panel();p.classList.add('hidden');const result=oldStart.apply(this,arguments);try{const pool=filter(),count=document.getElementById('count').value,n=count==='full'?pool.length:Number(count),key=document.getElementById('year').value+'|'+document.getElementById('subject').value;const seen=getSeen(),done=new Set(seen[key]||[]);let fresh=pool.filter(q=>!done.has(String(q.id)));if(fresh.length<n){fresh=pool;done.clear()}shuffle(fresh);quiz=fresh.slice(0,Math.min(n,fresh.length));quiz.forEach(q=>done.add(String(q.id)));seen[key]=[...done];setSeen(seen);cur=0;ans={};uncertain={};lastWrong=[];lastUncertain=[];render();}catch(e){console.warn('Question rotation fallback',e)}return result};
  setTimeout(function(){const actions=document.querySelector('#home .actions');if(actions&&!actions.querySelector('[data-local-stats]')){const b=document.createElement('button');b.className='secondary';b.textContent='📚 我的學習紀錄';b.dataset.localStats='1';b.onclick=showStats;actions.appendChild(b)}},300);
})();