/* Learning records and cross-device sync-code transfer. */
(function(){'use strict';
const KEY='sw_stats',SEEN='sw_seen_v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{attempts:[],questions:{}}}catch(_){return{attempts:[],questions:{}}}};
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function pack(){let seen={};try{seen=JSON.parse(localStorage.getItem(SEEN)||'{}')}catch(_){}return{format:'socialwork-sync',version:1,stats:read(),seen};}
function encode(d){const bytes=new TextEncoder().encode(JSON.stringify(d));let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return'SW1'+btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function decode(s){s=String(s).trim();if(s.startsWith('SW1'))s=s.slice(3);s=s.replace(/-/g,'+').replace(/_/g,'/');s+='='.repeat((4-s.length%4)%4);return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(s),c=>c.charCodeAt(0))));}
window.localExport=function(){const code=encode(pack());const w=window.open('','_blank');if(w){w.document.write('<meta charset="utf-8"><p>複製同步碼，貼到另一台裝置匯入：</p><textarea style="width:98%;height:70vh"></textarea>');const t=w.document.querySelector('textarea');t.value=code;t.select()}else prompt('請複製同步碼：',code)};
window.localImportPrompt=function(){const code=prompt('貼上舊裝置的同步碼（SW1 開頭）：');if(!code)return;try{const d=decode(code);if(d.format!=='socialwork-sync'||d.version!==1||!d.stats)throw Error();if(!confirm('將合併同步碼與本機紀錄，不會直接覆蓋。繼續？'))return;const old=read(),attempts=new Map();[...(old.attempts||[]),...(d.stats.attempts||[])].forEach(a=>attempts.set([a.at,a.score,a.total,a.correct].join('|'),a));const questions={...old.questions};Object.entries(d.stats.questions||{}).forEach(([id,b])=>{const a=questions[id]||{},q={...a,...b};['wrong','right','total','uncertain'].forEach(k=>q[k]=Math.max(Number(a[k]||0),Number(b[k]||0)));q.reasons={...(a.reasons||{}),...(b.reasons||{})};questions[id]=q});localStorage.setItem(KEY,JSON.stringify({attempts:[...attempts.values()].sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,100),questions});const seen=pack().seen;Object.entries(d.seen||{}).forEach(([k,v])=>seen[k]=[...new Set([...(seen[k]||[]),...(Array.isArray(v)?v:[])])]);localStorage.setItem(SEEN,JSON.stringify(seen));alert('匯入完成，紀錄已合併。');window.showStats();}catch(_){alert('同步碼無效，請重新複製。')}};
window.localExportFile=function(){const u=URL.createObjectURL(new Blob([JSON.stringify(pack(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='socialwork-backup.json';a.click();URL.revokeObjectURL(u)};
function controls(){return '<div class="wrong" id="syncControls"><h3>📚 我的學習紀錄／跨裝置同步</h3><p class="muted">在舊裝置匯出同步碼，再於新裝置匯入；不需註冊。</p><div class="actions"><button onclick="localExport()">📤 匯出同步碼</button><button class="secondary" onclick="localImportPrompt()">📥 匯入同步碼</button><button class="secondary" onclick="localExportFile()">下載備份檔</button></div></div>';}
function addEntry(){const actions=document.querySelector('#home .actions');if(actions&&!document.getElementById('syncEntry')){const b=document.createElement('button');b.id='syncEntry';b.className='secondary';b.textContent='📚 學習紀錄／同步碼';b.onclick=window.showStats;actions.appendChild(b)}}
const original=window.showStats;
window.showStats=function(){if(typeof original==='function')original();const review=document.getElementById('review');if(review){document.getElementById('syncControls')?.remove();review.insertAdjacentHTML('afterbegin',controls())}};
addEntry();
const observer=new MutationObserver(addEntry);observer.observe(document.body,{childList:true,subtree:true});
})();