/* Personal study UX: commute mode, smart review, mastery levels, keyword definitions and progress dashboard. */
(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const defs={
    '人在情境中':'理解個人問題時，同時考量其所處的家庭、社區、制度與社會文化脈絡。','生態系統觀點':'把個人與其直接、間接及更大社會環境視為彼此影響的系統來評估。','個人 ↔ 環境':'強調人的狀態與環境條件彼此作用，問題不只來自個人本身。','家庭／組織／社區':'常見的環境層次，協助社工從多層次理解服務對象的處境。','整體性評估':'綜合個人能力、需求、關係與環境因素，而非只看單一問題。',
    '專業關係':'社工與服務對象建立的具目的性、倫理性與專業界線的工作關係。','接納':'尊重服務對象的獨特性與當下狀態，不以個人價值判斷否定對方。','同理':'理解並回應服務對象的感受與觀點，同時維持專業角色。','合作目標':'由社工與服務對象共同討論並形成的工作方向與可達成目標。',
    '福利政策':'政府為回應社會需求所形成的福利措施、制度與資源安排。','資源分配':'決定有限的福利資源如何分配到不同需求、群體或服務領域。','公平／正義':'關注權利、機會與資源分配是否合理，以及不同群體是否受到公平對待。','制度設計':'將政策目標轉化為法規、服務、資格與執行機制的制度安排。',
    '發展階段':'以生命歷程理解個體在不同年齡階段的身心、心理與社會變化。','心理社會發展':'關注個體發展與人際、社會環境及生命任務之間的交互作用。','環境脈絡':'理解行為或發展時，將家庭、文化、社會與制度背景納入考量。',
    '信度':'測量工具結果的一致性或穩定程度。','一致性':'在相同或相近條件下，測量結果是否呈現一致。','穩定性':'同一測量在不同時間或重複測量時，結果是否穩定。','效度':'測量工具是否真正測量到原本想測量的概念或特質。','測量':'依一定規則將研究概念轉化為可觀察、可比較資料的過程。'
  };
  function stats(){try{return JSON.parse(localStorage.getItem('sw_stats')||'{"attempts":[],"questions":{}}')}catch{return {attempts:[],questions:{}}}}
  function score(q){const s=stats().questions[q.id]||{};let n=0;if((s.wrong||0)>=3)n+=100;if((s.uncertain||0)>0)n+=35;if((s.wrong||0)>=2&&(s.uncertain||0)>0)n+=40;if((s.wrong||0)>0)n+=Math.min(30,s.wrong*10);if((s.right||0)>=3&&!(s.wrong))n-=20;return n}
  function smartPool(mode){const bank=window.BANK||[];const s=stats();const qs=bank.filter(Boolean).map(q=>({q,score:score(q),seen:!!s.questions[q.id]}));if(mode==='commute')return qs.sort((a,b)=>b.score-a.score||Math.random()-.5).map(x=>x.q);return qs.sort((a,b)=>b.score-a.score).map(x=>x.q)}
  function startSmart(mode){if(!window.BANK||!window.BANK.length)return alert('正式題庫尚未載入。');const n=mode==='commute'?10:10;let pool=smartPool(mode);const seen=new Set();const selected=[];for(const q of pool){if(!seen.has(q.id)){selected.push(q);seen.add(q.id)}if(selected.length>=n)break}if(selected.length<n){const rest=window.BANK.filter(q=>!seen.has(q.id)).sort(()=>Math.random()-.5);selected.push(...rest.slice(0,n-selected.length))}window.quiz=selected;window.cur=0;window.ans={};window.uncertain={};window.lastWrong=[];window.lastUncertain=[];window.startedAt=Date.now();clearInterval(window.timerId);window.timerId=setInterval(window.updateTimer,1000);$('home').classList.add('hidden');$('result').classList.add('hidden');$('review').classList.add('hidden');$('quiz').classList.remove('hidden');window.render();window.updateTimer();const qtitle=document.createElement('div');qtitle.id='studyModeBadge';qtitle.className='tag';qtitle.textContent=mode==='commute'?'🚆 通勤模式｜優先複習弱點':'🎯 今日建議｜優先處理最需要複習的題目';$('qno').prepend(qtitle)}
  function addHome(){const home=$('home');if(!home||$('studyModeActions'))return;const box=document.createElement('div');box.id='studyModeActions';box.className='card';box.innerHTML='<h3 style="margin-top:0">⚡ 依你的學習狀況開始</h3><p class="muted">不用自己挑題。系統會優先安排曾錯、曾標記不確定、近期需要複習的題目。</p><div class="actions"><button onclick="studyStartCommute()">🚆 通勤模式｜10 題</button><button class="secondary" onclick="studyStartToday()">🎯 今日建議｜10 題</button></div><div id="studyQuickSummary" class="muted" style="margin-top:10px"></div>';home.parentNode.insertBefore(box,home);renderQuickSummary()}
  function renderQuickSummary(){const e=$('studyQuickSummary');if(!e)return;const s=stats(),v=Object.values(s.questions||{}),weak=v.filter(x=>(x.wrong||0)>=3||((x.uncertain||0)>0&&(x.wrong||0)>=2)).length,unc=v.filter(x=>(x.uncertain||0)>0).length;e.textContent=`目前：🔴 高優先 ${weak} 題｜⚑ 曾不確定 ${unc} 題｜累積模擬考 ${(s.attempts||[]).length} 次`}
  function renderMastery(){const r=$('review');if(!r)return;const s=stats(),qs=Object.entries(s.questions||{}),high=qs.filter(([,v])=>(v.wrong||0)>=3),need=qs.filter(([,v])=>(v.wrong||0)>0&&!(v.wrong>=3)),unc=qs.filter(([,v])=>(v.uncertain||0)>0&&!(v.wrong>=2&&v.uncertain>0)),master=qs.filter(([,v])=>(v.right||0)>=3&&(v.wrong||0)===0);let box=document.getElementById('masteryBox');if(box)box.remove();box=document.createElement('div');box.id='masteryBox';box.className='card';box.innerHTML='<h3>🎯 題目掌握程度</h3><div class="statgrid"><div class="stat"><small>🔴 高優先</small><b>'+high.length+'</b><span class="meta">錯 3 次以上</span></div><div class="stat"><small>🟠 需要複習</small><b>'+need.length+'</b><span class="meta">曾答錯</span></div><div class="stat"><small>🟡 不確定</small><b>'+unc.length+'</b><span class="meta">猜對也算</span></div><div class="stat"><small>🟢 已掌握</small><b>'+master.length+'</b><span class="meta">連續答對且無錯</span></div></div>';r.insertBefore(box,r.firstChild)}
  function trend(){const s=stats(),a=(s.attempts||[]).slice().reverse();return a.map(x=>x.score).slice(-10)}
  function renderTrend(){const r=$('review');if(!r||r.classList.contains('hidden'))return;let old=document.getElementById('studyTrend');if(old)old.remove();const t=trend();if(!t.length)return;const d=document.createElement('div');d.id='studyTrend';d.className='card';d.innerHTML='<h3>📈 最近模擬考趨勢</h3><div class="muted">最近 '+t.length+' 次：'+t.map((x,i)=>`第 ${i+1} 次 <b>${x}%</b>`).join('　→　')+'</div><div style="margin-top:12px;font-family:ui-monospace,monospace;letter-spacing:1px">'+t.map(x=>'▁▂▃▄▅▆▇█'[Math.min(7,Math.floor(x/12))]).join(' ')+'</div>';r.insertBefore(d,r.firstChild)}
  window.studyStartCommute=()=>startSmart('commute');window.studyStartToday=()=>startSmart('today');
  const oldGo=window.goHome;if(typeof oldGo==='function')window.goHome=function(){oldGo();setTimeout(()=>{addHome();renderQuickSummary()},0)};
  const oldShowStats=window.showStats;if(typeof oldShowStats==='function')window.showStats=function(){oldShowStats();setTimeout(()=>{renderMastery();renderTrend()},20)};
  window.toggleMind=function(btn,s){const m=btn.parentElement.nextElementSibling;const arr=(window.mind&&window.mind[s])||[];m.className='mind show';m.innerHTML='<div class="chain">'+arr.map((x,i)=>(i?'<span class="arrow">→</span>':'')+'<button class="node mind-node" onclick="showKeywordDef(this)" data-key="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><div class="keyword-def muted" style="margin-top:12px">點擊任一名詞，直接查看對應解釋。</div>'};
  window.showKeywordDef=function(btn){const key=btn.dataset.key||'';const box=btn.closest('.mind').querySelector('.keyword-def');const d=defs[key]||'目前尚未建立這個名詞的個人筆記。建議後續把題庫中高頻、易混淆名詞補進名詞庫。';box.className='keyword-def explain';box.innerHTML='<b>🔑 '+esc(key)+'</b><br>'+esc(d)};
  setTimeout(addHome,500);
})();
