/* STUDY_REVIEW_V3 */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  function stGet(){try{return JSON.parse(localStorage.getItem('sw_stats')||'{"attempts":[],"questions":{}}')}catch{return{attempts:[],questions:{}}}}
  function stSet(s){localStorage.setItem('sw_stats',JSON.stringify(s))}
  window.showReview=function(){
    $('result').classList.add('hidden');if($('keywordPage'))$('keywordPage').classList.add('hidden');$('review').classList.remove('hidden');
    const rows=Array.isArray(window.lastWrong)?window.lastWrong:[];const st=stGet();
    let html='<h2>錯題檢討</h2><div class="keywordbar"><input id="reviewKeywordSearch" placeholder="🔎 搜尋關鍵名詞，例如：創傷知情" onkeydown="if(event.key===\'Enter\')openKeywordPageBySearchV3()"><button class="secondary" onclick="openKeywordPageBySearchV3()">關鍵名詞搜索</button></div>';
    if(!rows.length){$('review').innerHTML=html+'<p>本次沒有錯題。</p>';return}
    html+=rows.map(({x,a})=>{const q=st.questions[x.id]||{};const mine=a==null?'未作答':String.fromCharCode(65+a);const correct=String.fromCharCode(65+x.answer);const marked=Array.isArray(window.lastUncertain)&&window.lastUncertain.some(z=>z.x.id===x.id);const ks=typeof keywordMatches==='function'?keywordMatches(x):[];return `<div class="wrong"><b>${esc(x.year)}｜${esc(x.subject)}｜第 ${esc(x.number)} 題</b>${marked?'<span class="tag">⚑ 曾標記不確定</span>':''}<p>${esc(x.question)}</p><p>你的答案：${mine}｜正確答案：<b>${correct}</b></p><div class="explain"><b>📌 解析</b><br>${esc(x.explanation||'本題目前沒有提供解析。')}${x.source?`<br><span class="meta"><a href="${esc(x.source)}" target="_blank" rel="noopener">原始題目來源</a></span>`:''}</div>${ks.length?`<div class="keywordbar"><b>🔑 本題關鍵名詞：</b>${ks.map(k=>`<button class="keywordbtn" onclick="openKeywordPage('${String(k).replaceAll("'","\\'")}')">${esc(k)}</button>`).join('')}</div>`:''}<div class="reason">${['完全不會','觀念混淆','選項搞混','看錯題目','粗心／判斷失誤','法規／年份記錯'].map(r=>`<button class="secondary" onclick="reasonV3('${String(x.id).replaceAll("'","\\'")}','${r}')">${r}</button>`).join('')}</div><small id="reasonv3_${esc(x.id)}"></small><div class="actions"><button class="secondary" onclick="toggleMind(this,'${esc(x.subject)}')">🧠 關鍵字心智擴散</button></div><div class="mind"></div><p class="meta">本題累計錯誤：${q.wrong||0} 次｜曾標記不確定：${q.uncertain||0} 次</p></div>`}).join('');
    $('review').innerHTML=html;
  };
  window.reasonV3=function(id,r){const st=stGet(),q=st.questions[id]||{wrong:0,right:0,total:0,uncertain:0,reasons:{}};q.reasons=q.reasons||{};q.reasons[r]=(q.reasons[r]||0)+1;st.questions[id]=q;stSet(st);const e=$('reasonv3_'+id);if(e)e.textContent=`已記錄「${r}」｜本題錯 ${q.wrong||0} 次`};
  window.openKeywordPageBySearchV3=function(){const q=$('reviewKeywordSearch').value.trim();if(!q){if(typeof openKeywordPage==='function')openKeywordPage('創傷知情');return}if(typeof allKeywords==='function'){const k=allKeywords().find(x=>x===q||x.includes(q));if(k&&typeof openKeywordPage==='function'){openKeywordPage(k);return}}if(typeof openKeywordPage==='function'){openKeywordPage('創傷知情');if($('keywordSearch')){$('keywordSearch').value=q;if(typeof searchKeywords==='function')searchKeywords()}}};
  window.showWeak=function(){const st=stGet();const rows=Object.entries(st.questions).filter(([id,q])=>Number(q.wrong||0)>=3||(Number(q.uncertain||0)>0&&Number(q.wrong||0)>=2));$('result').classList.add('hidden');if($('keywordPage'))$('keywordPage').classList.add('hidden');$('review').classList.remove('hidden');$('review').innerHTML=`<h2>🎯 個人加強區</h2><p>符合條件：① 同一題錯 3 次以上；或 ② 曾標記不確定＋錯 2 次以上。</p><p><b>${rows.length}</b> 題需要優先加強。</p>`+(rows.length?rows.map(([id,q])=>{const x=(typeof BANK!=='undefined'?BANK:[]).find(z=>z.id===id);return x?`<div class="wrong"><b>${esc(x.year)}｜${esc(x.subject)}｜第 ${esc(x.number)} 題</b><p>${esc(x.question)}</p><p class="meta">錯 ${q.wrong||0} 次｜答對 ${q.right||0} 次｜不確定 ${q.uncertain||0} 次</p><div class="actions"><button class="secondary" onclick="window.setStudyMode&&window.setStudyMode('fast');alert('請從首頁選擇相同篩選條件後進入快問快答重做本題。')">🎯 再挑戰</button><button class="secondary" onclick="openKeywordFromQuestionV3('${String(id).replaceAll("'","\\'")}')">🔑 查看關鍵名詞</button></div></div>`:''}).join(''):'<p>目前沒有符合條件的題目，繼續累積作答即可。</p>')};
  window.openKeywordFromQuestionV3=function(id){const x=(typeof BANK!=='undefined'?BANK:[]).find(z=>z.id===id);if(!x||typeof keywordMatches!=='function')return;const k=keywordMatches(x)[0];if(k&&typeof openKeywordPage==='function')openKeywordPage(k);else alert('這題目前沒有可辨識的核心名詞。')};
})();
